language: node_js

node_js:
  - "stable"

cache:
  directories:
  - node_modules

script:
  - yarn test:unit
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: dist
  verbose: true